### PR TITLE
Fix #37.

### LINKED ISSUE #37: [Bug] Broken build.
Bertie currently uses git dependencies, e.g., ...

```toml
hacspec_cryptolib = { git = "https://github.com/cryspen/utils", optional = true, package = "hacspec_cryptolib" }
```

Due to the deletion of a branch, `hacspec_cryptolib` could not be build and the bertie build failed, too. [9d46aaf9a6d4ffdd8ef1e20f760dee818ec95631](https://github.com/cryspen/utils/commit/9d46aaf9a6d4ffdd8ef1e20f760dee818ec95631) fixed the broken build. However, in the meantime, the signature of the `verification_key_from_cert` function changed from ...

```rust
fn verification_key_from_cert(cert: &ByteSeq) -> Result<VerificationKey, CryptoError>
```

... to ...

```rust
fn verification_key_from_cert(cert: &ByteSeq) -> SpkiResult
```

This has to be adjusted in bertie, too.

### PR DESCRIPTION
**Pull request by duesee**
This PR addresses broken build described in issue #37.

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation
- [ ] Automation

## Checklist
- [x] I have linked an issue to this PR
- [x] I have described the changes
- [x] I have read and understood the code of conduct, contribution guidelines, and contributor license agreement
- [x] I have added tests for all changes
- [x] I have tested that all tests pass locally and all checks pass
- [x] I have updated documentation if necessary

Fixes #37

### CODE REVIEW

File: src/tls13handshake.rs [hunk 1]
```diff
@@ -298,9 +298,20 @@ fn put_server_signature(
         let cert = parse_server_certificate(&algs, sc)?;
         let tx = transcript_add1(tx, sc);
         let th_sc = get_transcript_hash(&tx)?;
-        let pk = verification_key_from_cert(&cert)?;
+        let (signature_scheme, certificate_key) = verification_key_from_cert(&cert)?;
         let sig = parse_certificate_verify(&algs, scv)?;
         let sigval = PREFIX_SERVER_SIGNATURE.concat(&th_sc);
+        // TODO(Refactor): This is used because the API of `evercrypt_cryptolib::verify` wants a `PublicVerificationKey`.
+        //                 That enum is directly unpacked in `verify`, though.
+        let pk = match signature_scheme {
```
Comment (franziskuskiefer) [inline src/tls13handshake.rs:306]: This (`let match`) is not allowed in hacspec.

**Review by franziskuskiefer — CHANGES_REQUESTED** [review]

File: src/tls13handshake.rs (hunk 1 above)
Comment (duesee) [reply src/tls13handshake.rs]: Right. Didn't verified it yet because priority was to make it build again :-) But let's not introduce code that is invalid according to hacpsec.

File: src/tls13handshake.rs [hunk 2]
```diff
@@ -298,10 +298,22 @@ fn put_server_signature(
...
         let sig = parse_certificate_verify(&algs, scv)?;
         let sigval = PREFIX_SERVER_SIGNATURE.concat(&th_sc);
-        verify(&sig_alg(&algs), &pk, &bytes(&sigval), &sig)?;
+        // TODO(Refactor): This is used because the API of `evercrypt_cryptolib::verify` wants a `PublicVerificationKey`.
+        //                 That enum is directly unpacked in `verify`, though.
+        if signature_scheme == SignatureScheme::EcdsaSecp256r1Sha256 {
+            let verification_key = ecdsa_public_key(&cert, certificate_key)?;
+            let pk = PublicVerificationKey::EcDsa(verification_key);
+            verify(&sig_alg(&algs), &pk, &bytes(&sigval), &sig)?;
+        } else if signature_scheme == SignatureScheme::RsaPssRsaSha256 {
```
Comment (franziskuskiefer) [inline src/tls13handshake.rs:310]: Neither do we have `else if` or inline blocks. See https://github.com/hacspec/hacspec/issues/85 for the `else if` issue.

**Review by franziskuskiefer — APPROVED** [review]
This still won't typecheck in hacspec. But I'm fine with this for now. It'll need to be changed again anyway.
